### ISSUE TITLE
Add support for queue timeout

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1086]
A new feature is now available in LAVA to enable queue timeouts: https://git.lavasoftware.org/lava/lava/-/issues/473

This can be used by KernelCI to ensure that jobs don't pile up for ever in the lab queues.  It could be added as an attribute in the YAML configuration so each lab could set its own timeout value, or not at all to not enable the feature.  For example:

```yaml
  lab-something:
    lab_type: lava.lava_xmlrpc
    url: 'https://lava.something.org/RPC2/'
    priority: low
    queue_timeout:
      hours: 24
    filters:
      - passlist:
          plan:
            - baseline
            - kselftest
```

The timeout could be defined with a dictionary containing any combination of days, hours and minutes.

The current expectation is that the queue timeout should be a last-resort mechanism for cancelling jobs that are clearly not useful to keep in the queue because new kernel revisions have been pushed since. So having a global value for each lab should be fine, but if we need very long timeouts for some trees like stable and shorter ones for others then we could add something later to make it tree-specific.
