### ISSUE TITLE
k8s job deadline

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1492]
Right now as we submit job to k8s in jenkins, jenkins job often have deadline set (usually) 45m. As i noticed, in many cases when k8s builders are too busy, jenkins might submit job, but because there is no available resources - wait.py will quit by timeout.
But! Jobs in kubernetes still exist, like now:
```
build-j435127-i386-clang-11-allmodconfig                       0/1           2d2h       2d2h
build-j435549-arm-clang-14-allmodconfig                        1/1           45h        2d
build-j436214-x86-64-gcc-10-allmodconfig                       0/1           45h        45h
build-j436629-arm64-clang-16-allmodconfig                      0/1           44h        44h
build-j436707-arm-clang-14-allmodconfig                        0/1           44h        44h
build-j436824-arm64-gcc-10-gki-defconfig                       0/1           44h        44h
build-j436957-arm64-clang-14-gki-defconfig                     0/1           43h        43h
build-j436959-arm64-clang-14-allmodconfig                      0/1           43h        43h
```
And as in jenkins nobody "wait" them anymore, it is practically wasted computing resource.
To mitigate that i believe we need to set deadline for jobs, for example activeDeadlineSeconds (not sure if it fits requirements).

**Comment by broonie** [comment]
activeDeadlineSeconds would fit the bill there, however I'd expect that once we switch to pipeline we won't have this issue - it is a big part of the changes I've been pushing to just push the jobs into Kubernetes without waiting.

Also do we not post the results from the builds directly from the build job so even if we don't kick any tests we'll still get the build resutls?

**Comment by mgalka** [comment]
@broonie You're right. We're getting results from the build job directly, so even if the "wait" will reach a timeout we won't lose the build results and won't schedule test jobs.

There is however one more thing. When a k8s job is scheduled it spawns pods, when spawning pods fails the job will continue to respawn them forever. In a situation when "waiting" in Jenkins has timed out we lose track of what's happening in a k8s cluster so eventually if there are many undone jobs in the cluster we may end up with builders jammed and not being aware of that. We've faced similar situation recently, when a minor config issue generated a job which pods were not able to complete successfully and the undone job was respawning them forever. I believe setting up a activeDeadlineSeconds to some big, but reasonable value could save us trouble in future.

**Comment by broonie** [comment]
If the pods are actually failing then backoffLimit is probably a better thing to use here - we do want some retries because one reason for failure is spot instance preemption. Setting a large timeout on the job would mean that failing jobs would keep on getting restarted holding resources each time it gets started, while a backoffLimit means that we give up after some number of retries.

**Comment by nuclearcat** [comment]
That makes sense, i will try to make PR monday on backoffLimit and we might do "faulty" job artificially and see how it goes.

**Comment by nuclearcat** [comment]
I am wondering if backoffLimit will work at all, take a look: https://github.com/kubernetes/kubernetes/issues/101584
If this issue not resolved...

**Comment by broonie** [comment]
The issue you referenced with backoffs not working is specific to imagePullBackoff AFAICT:

https://github.com/kubernetes/kubernetes/issues/101584#issuecomment-833281793

which shouldn't be the issue we're seeing.

**Comment by nuclearcat** [comment]
You are right, i tried to reproduce invalid docker image situation, and it seems it keep looping.
template to reproduce is simplified "build" job is below.

Also i am not sure there is any solution to that (at least i am not able to find any), except we can add additional step in jenkins to verify that docker image exist.

P.S. Do you suggest to revert patch?
```
apiVersion: batch/v1
kind: Job
metadata:
  name: invalidimagejob

spec:
  completions: 1
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure

      # in-memory tmpfs
      volumes:
      - name: scratch-volume
        emptyDir: { medium: "Memory" }

      # only run on preemptible nods
      #nodeSelector:
      #  cloud.google.com/gke-preemptible: "true"

      # tolerate Azure spot instances
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"

      initContainers:
      - name: scratch-setup
        image: kernelci/wrong-image-name

        volumeMounts:
        - mountPath: "/scratch"
          name: scratch-volume

        command: ["/bin/bash", "-x", "-c"]
        args: ["mkdir -p /tmp/kci"]

      containers:
      - name: kci-build
        image: kernelci/wrong-image-name
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/scratch"
          name: scratch-volume

        # Run as root so the build artifacts have root uid:gid set on them
        securityContext:
          runAsUser: 0
          runAsGroup: 0

        command: ["/bin/bash", "-x", "-c"]
        args: ["\
echo nproc=$(nproc); df; free; whoami; \
exit 0; \
"]


```
