### ISSUE TITLE
Remove armv3 config (rpc_defconfig) from gcc builds

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1508]
According https://www.phoronix.com/news/GCC-9-Dropping-Older-ARM gcc dont have support for armv3 for quite long time.
```
rpc_defconfig (arm, gcc-10) — FAIL, 2 errors, 0 warnings, 0 section mismatches

Errors:
    arm-linux-gnueabihf-gcc: error: unrecognized -march target: armv3
    arm-linux-gnueabihf-gcc: error: missing argument to ‘-march=’
```
It seems rpc_defconfig should be removed from testing by recent versions of gcc
