### ISSUE TITLE
Trees for removal or to be fixed

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1513]
Trees from configuration:
stable-rc_queue-5.20
stable-rc_5.20
stable_5.20
broonie-sound-fixes

Give 404 during repository check for new commits. Probably trees doesnt exist anymore and need to be removed?
If confirmed - i will do that.
@broonie @gctucker

**Comment by broonie** [comment]
Can you provide a concrete example of the issue you believe exists with my tree? Nothing has changed with the tree in years...

**Comment by nuclearcat** [comment]
./kci_build check_new_commit --build-config=broonie-sound-fixes --storage=http://storage.kernelci.org
get_last_commit() HTTP error: 404

```
  broonie-sound-fixes:
    tree: broonie-sound
    branch: 'for-next-linus'

  broonie-sound:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git"

```
As far as i see such branch (for-next-linus) doesn't exist.
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/log/?h=for-next-linus
