### ISSUE TITLE
Add per-API config for LAVA callback

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#2088]
The LAVA runtime YAML config currently expects something like this for the callbacks:
```yaml
    notify:
      callback:
        token: kernelci-api-token-staging
        url: https://staging.kernelci.org:9100
```
However, the token name and URL will vary depending on the API instance being used.  One option is to add a mapping to provide notify blocks for each API config name, e.g.:
```yaml
    notify:
      staging: 
        callback:
          token: kernelci-api-token-staging
          url: https://staging.kernelci.org:9100
      early-access:
        callback:
          token: kernelci-api-token-early-access
          url: https://staging.kernelci.org:9100
```
Another option is to rely on a convention for the token name and only have one callback URL per runtime, effectively making the callback handler a logic part of the runtime.  The first option is probably a better choice though.
