### ISSUE TITLE
Splitting pipeline.yaml to multiple files

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2120]
This is related to https://github.com/kernelci/kernelci-core/discussions/1907

In current design we have single pipeline.yaml that includes multiple sections . While during the initial testing it is convenient, when we will add tens of trees, build configurations, devices, test plans it will be much harder to maintain and contribute.

I propose 2 solutions that will allow us to split config file to multiple.
1)Simple custom Loader class:
```python
class Loader(yaml.SafeLoader):
    def __init__(self, stream):
        self._root = os.path.split(stream.name)[0]
        super(Loader, self).__init__(stream)

    def include(self, node):
        filename = os.path.join(self._root, self.construct_scalar(node))
        with open(filename, "r") as f:
            return yaml.load(f, Loader)


Loader.add_constructor("!include", Loader.include)
```
This way main configuration file will look like this:
```yaml
api_configs: !include pipeline-api.yaml
storage_configs: !include pipeline-storage.yam
runtimes: !include pipeline-runtimes.yaml
jobs: !include pipeline-jobs.yaml
trees: !include pipeline-trees.yaml

```
and for example pipeline-api.yaml
```yaml
  docker-host:
    url: http://172.17.0.1:8001

  staging:
    url: https://staging.kernelci.org:9000

  early-access:
    url: https://kernelci-api.eastus.cloudapp.azure.com

  k8s-host:
    url: http://kernelci-api:8001
```
Pros: easy to maintain
Cons: Doesn't allow more complex includes.

2)https://pypi.org/project/pyyaml-include/ which is similar and self-explanatory.
Pros: allowed more complex include scenarios
Cons: one more dependency to maintain
