### ISSUE TITLE
Convert kernelci package to pyproject.toml

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#2283]
Today's recommended way to manage a Python package is by creating a `pyproject.toml` file.  Converting the existing `setup.py` file would seem like a requirement before starting to publish the `kernelci` pakcage again on PyPI.

See the documentation about [Writing your `pyproject.toml`](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/) for more details.  The `hatchling` build backend works fine for regular Python packages such as `kernelci`.

**Comment by gctucker** [comment]
Basically, something like this:
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kernelci"
version = "0.99"
requires-python = ">= 3.8"
dependencies = [
  "pydantic==1.10.4",
  "requests==2.31.0",
]
scripts.kci = "kernelci.cli.main"
authors = [
  {name = "Guillaume Tucker", email = "gtucker@gtucker.io"},
]
```
with all the current authors and maintainers, details about the LGPL license, full list of dependencies, URLs for the kernelci.org website and GitHub repository etc.

FWIW, I happen to have done something similar for another project recently using `setuptools` as the build backend since that required some features not really supported with pure `pyproject.toml` (C extension):
https://gitlab.com/verdigris.org/splat/-/commit/1fbd69e3871263b0d608897e794e83b3315c6de3
