### ISSUE TITLE
Support for scheduled tree checkouts

### ISSUE THREAD

**Issue by laura-nao** [kernelci/kernelci-core#2857]
Currently, KernelCI allows scheduling limitations only for jobs, using the `frequency` parameter - e.g.:
```
  kbuild-clang-17-chromeos:
    params: &kbuild-clang-17-chromeos-params
      compiler: clang-17
      defconfig: 'cros://chromeos-{krev}/{crosarch}/chromiumos-{flavour}.flavour.config'
      flavour: '{crosarch}-generic'
      kselftest: disable
      frequency: 1d
```

When a new commit is pushed to a tree that has already been built/tested that day, a checkout node is still created - even though no actual build or test is triggered. As a result, the `Trees` view on the web dashboard shows zeros for `Build Status`, `Boot Status`, and `Test Status` (see e.g. https://dashboard.kernelci.org/tree?ts=chromeos). To see the latest results, users need to click into the tree entry and browse through the history manually.

It would be helpful to have an option to limit the frequency of the checkouts, to avoid generating empty nodes and improve overall usability for users.
